### ISSUE TITLE
Problem login

### ISSUE THREAD

**Issue by coret** [AtomGraph/LinkedDataHub#124]
I've followed the setup instructions (including importing cert in Chrome) but when I load https://localhost:4443/ I get the following error:

**WebID profile could not be loaded: https://localhost:4443/admin/acl/agents//#this**

```
<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:j.0="http://purl.org/dc/terms/"
    xmlns:j.1="http://www.w3.org/2011/http#" > 
  <rdf:Description rdf:nodeID="A0">
    <j.0:title>WebID profile could not be loaded: https://localhost:4443/admin/acl/agents//#this</j.0:title>
    <j.1:sc rdf:resource="http://www.w3.org/2011/http-statusCodes#BadRequest"/>
    <j.1:reasonPhrase>Bad Request</j.1:reasonPhrase>
    <j.1:statusCodeValue rdf:datatype="http://www.w3.org/2001/XMLSchema#long">400</j.1:statusCodeValue>
    <rdf:type rdf:resource="http://www.w3.org/2011/http#Response"/>
  </rdf:Description>
</rdf:RDF>
```

In the (Docker) logfile I see:

`linkeddatahub_1     | 12:41:25,998 [http-nio-7070-exec-5] ERROR WebIDFilter:286 - Could not load WebID Agent: https://localhost:4443/admin/acl/agents//#this`

What am I missing?

**Comment by namedgraph** [comment]
Hi Bob,

The WebID URI looks wrong.

I suspect the setup.sh did not succeed. Can you check the log for any errors around that?

What OS are you on? The setup currently requires Bash version 4.

**Comment by namedgraph** [comment]
Thanks, that's useful feedback! Will add a check for `uuid`.

Let us know what your use case and/experience with LinkedDatHub is.
