### ISSUE TITLE
Got Error 500 when tried to access admin page.

### ISSUE THREAD

**Issue by FNakano** [AtomGraph/LinkedDataHub#136]
Hi!
   I tried to follow the SKOS tutorial. It instructs to access ontology by clicking on configuration->admin menu item., got Error 500 (screenshot below)

![Captura de tela de 2022-10-06 10-04-14](https://user-images.githubusercontent.com/14809968/194321033-c34938ea-fa60-47a2-a076-d7e45dccdb74.png)

   This time I ran LinkedDataHub with `docker-compose up 2>&1 | tee 20221006-10:03.run.log` so I have a 22MB log. I can send it to you, if needed.
    How can I fix the error and get to admin page?

**Comment by namedgraph** [comment]
I see there was a 429 error in the log which happens when nginx receives too many requests, in this case too many stylesheets are being loaded at the same time.
Can you try simple hard refresh (Ctrl+F5)? :)

**Comment by FNakano** [comment]
Thanks for your reply.
Unfortunately, CTRL-F5 resulted in the same page displayed...
The request was sent (a lot of messages in the terminal). I can send you a screen capture video.

**Comment by namedgraph** [comment]
`docker-compose logs --tail 500 linkeddatahub > ldh.log` should generate a log file with enough info.

What if you tried increasing the `rate` value for `static_files` in the `platform/nginx.conf.template` config file?
```
    limit_req_zone $binary_remote_addr zone=static_files:10m rate=20r/s;
```

**Comment by FNakano** [comment]
I got the logs before changing `limit_req_zone $binary_remote_addr zone=static_files:10m rate=6r/s;` to `limit_req_zone $binary_remote_addr zone=static_files:10m rate=20r/s;` and after changing it.
--------------- before
[ldh-before.log](https://github.com/AtomGraph/LinkedDataHub/files/9726792/ldh-before.log)

----------------- after
[ldh-after.log](https://github.com/AtomGraph/LinkedDataHub/files/9726797/ldh-after.log)

**Comment by namedgraph** [comment]
The error is the same.

The file already contained `zone=static_files:10m rate=20r/s`? Try increasing `rate` to 50 or so.
Also try increasing `burst` in `limit_req zone=static_files burst=20 nodelay`.

Alternatively you can try commenting out `limit_req_zone` statements altogether and see if that helps.

**Comment by FNakano** [comment]
Hi!
.... it was 6. I tried increasing it to 20.
   This time I increased it from 20 to 100, resulting in `limit_req_zone $binary_remote_addr zone=static_files:10m rate=100r/s;`. It solved the error 500.
![Captura de tela de 2022-10-07 08-51-36](https://user-images.githubusercontent.com/14809968/194547022-2bc728ff-f83c-490a-bbc9-c54b1ffea673.png)
   I will keep trying LinkedDataHub.
   Thanks for your help.

**Comment by namedgraph** [comment]
@FNakano can you tell us something about your use case, if any?

**Comment by FNakano** [comment]
I apologize to take so long to answer...
I'm interested to apply knowledge graphs/knowledge enrichment on sensor data and use it to suggestion/decision making... also some kind of (semi-)automatic document generation (using SKOS, Dublin Core, ...)
