### ISSUE TITLE
Type Ahead did not suggest construct query and file on CSV import

### ISSUE THREAD

**Issue by FNakano** [AtomGraph/LinkedDataHub#138]
I tried to import CSV data using `[LinkedDataHub] User guide - CSV import` video and https://atomgraph.github.io/LinkedDataHub/linkeddatahub/docs/reference/imports/csv/#vocabulary-conversion as references.

1. Created a `countries.csv` file from https://atomgraph.github.io/LinkedDataHub/linkeddatahub/docs/reference/imports/csv/#vocabulary-conversion fist file listing;
2. Created a construct query from https://atomgraph.github.io/LinkedDataHub/linkeddatahub/docs/reference/imports/csv/#vocabulary-conversion third file listing
3. Tried to create a CSV Import: typeahead for `file` and `query` did not suggest any file nor query (screenshot below).

![Captura de tela de 2022-10-28 22-18-19](https://user-images.githubusercontent.com/14809968/198759868-384dee6b-f0da-4903-b31d-4423417cf3d2.png)

Also tried capitalizing first letter, same result.

Curiously, typeahead suggested a constructor (not a construct query)

![photo1667008510](https://user-images.githubusercontent.com/14809968/198764670-36665016-6a22-44ec-9543-79a60b418214.jpeg)

**Comment by namedgraph** [comment]
Thanks for the report, will investigate ASAP.

**Comment by FNakano** [comment]
Hello!
    Procedure to get the log:
1. Removed the CSV import resource created in the previous tries;
2. Removed the File resource;
3. Removed the CONSTRUCT queries related to the issue.

From this clean(?) start:

1. In the Root container, create new File, get `countries.csv` from the filesystem, Label it `countries`;
2. In the Root container, create new CONSTRUCT, fill in the query text with the query from https://atomgraph.github.io/LinkedDataHub/linkeddatahub/docs/reference/imports/csv/, label it `countries`;
3. In the Root container, create new  CSV Import;
    4. Type 'cou' in File text box (got no suggestion);
    5. Type 'cou' in Query text box (got no suggestion);
6. Generate log with `docker-compose logs --tail 500 linkeddatahub >importCSV-typeahead-issue-138.log`

[importCSV-typeahead-issue-138.log](https://github.com/AtomGraph/LinkedDataHub/files/9894435/importCSV-typeahead-issue-138.log)

:)

**Comment by namedgraph** [comment]
@FNakano this could be to the broken multiple-type support in the typeahead component which went unnoticed for some time. I fixed this accidentally in the `develop` branch just a few days ago :) Would you be able to try this with the latest `develop` code?

**Comment by namedgraph** [comment]
Now released as 3.2.23 and on `master` as well.

**Comment by FNakano** [comment]
Hello!
   Yes! TypeAhead in master branch showed the same suggestions.
   I'm going to close the issue...
... it is a somehow related doubt:
   Which one should I choose - the ArchiveItem or the FileDataObject?

Thank you!
