### ISSUE TITLE
Import CSV: did not find 'Target container' input box

### ISSUE THREAD

**Issue by FNakano** [AtomGraph/LinkedDataHub#141]
Hello!
    In create New -> CSV Import I did not find a *target container* input box (as indicated in video https://youtu.be/vkuO6RiTW9s?list=PLnDXST4pVcQQr-j3YXrVvGRP46E2Nnn5l, 3min 26s). I believed *has Container* would be the same but it is not.
    After creating the CSV Import, its parent container showed the CSV Import description. I expected it would contain a sequence of countries, similar to the sequence of places in the video at 4:30.

![Captura de tela de 2022-10-31 15-57-26](https://user-images.githubusercontent.com/14809968/199090737-318e545e-3239-4d53-9c44-48b53da07d42.png)

   What am I missing?

**Comment by namedgraph** [comment]
@FNakano that video is quite out of date I'm afraid... We'll try to make a new version soon.

The "Target container" is gone. Now it's the `CONSTRUCT` query that controls explicitly what container the document attaches to using the `sioc:has_container` property. See some CSV import query examples:
https://github.com/AtomGraph/LinkedDataHub-Apps/blob/master/demo/northwind-traders/queries/imports/

Thank you for your effort :)
