### ISSUE TITLE
Support for linux/arm(64/v8) docker images

### ISSUE THREAD

**Issue by beepsoft** [AtomGraph/LinkedDataHub#149]
Hi,

I just tried to install LinkedDataHub on my development M1 MacBook Pro and `docker-compose` fails with:

```
linkeddatahub-varnish-end-user-1  | Error:
linkeddatahub-varnish-end-user-1  | Message from VCC-compiler:
linkeddatahub-varnish-end-user-1  | Assert error in vju_subproc(), mgt/mgt_jail_unix.c line 212:
linkeddatahub-varnish-end-user-1  |   Condition((initgroups(vju_user, vju_gid)) == 0) not true.
linkeddatahub-varnish-end-user-1  |   errno = 1 (Operation not permitted)
linkeddatahub-varnish-end-user-1  | qemu: uncaught target signal 6 (Aborted) - core dumped
linkeddatahub-varnish-end-user-1  | Running VCC-compiler failed, signal 6
linkeddatahub-varnish-end-user-1  | VCL compilation failed
```

As I see all atomgraph images on dockerhub support only `linux/amd64`. Most of them seem to work fine (although quite slow) via qemu on M1, but the `atomgraph/varnish:6.0.11` images used by the `varnish-admin` and `varnish-end-user` services fail with the above error.

Would it be possible to build and publish images to dockerhub supporting `linux/arm64/v8` as well? Or provide a workaround to build these images when running `docker-compose up --build` in LinkedDataHub?

**Comment by namedgraph** [comment]
Thanks for the report. Hard to say anything right now because my `docker-compose up --build` on M1 hangs on this Dockerfile command:
https://github.com/AtomGraph/LinkedDataHub/blob/master/Dockerfile#L175

Supposedly there's a way to [run Docker with Rosetta on Mac](https://levelup.gitconnected.com/docker-on-apple-silicon-mac-how-to-run-x86-containers-with-rosetta-2-4a679913a0d5), but I don't see that option under "Features in development" :/

**Comment by namedgraph** [comment]
After running Terminal in Rosetta, I get the same error. No idea what the cause is :) I'll write to the Varnish list.

**Comment by namedgraph** [comment]
Varnish list thread: https://www.mail-archive.com/varnish-misc@varnish-cache.org/msg08744.html

**Comment by beepsoft** [comment]
> Thanks for the report. Hard to say anything right now because my `docker-compose up --build` on M1 hangs on this Dockerfile command: https://github.com/AtomGraph/LinkedDataHub/blob/master/Dockerfile#L175
> 

I also encountered this. But after a couple of trials it _did_ execute all the `keytool -import` commands.

As for Varnish: my current workaround is that I copied the contents of https://github.com/AtomGraph/varnish to LinkedDataHub and used

```yaml
  varnish-admin:
    build: ./varnish
```

instead of 

```yaml
  varnish-admin:
    image: atomgraph/varnish:6.0.11
```

in docker-compose.yaml. With all these and with a little luck with `./import-letsencrypt-stg-roots.sh` I could start the project.

Anyways, thanks for taking care of M1 issues!

**Comment by beepsoft** [comment]
I am running Docker Desktop 4.16.2 (95914), Docker Engine Engine: 20.10.22 and just tried the "Use Rosetta for x86/amd64 emulation on Apple Silicon" option. Now it seems to start all right with the stock `docker-compose.yml`:

```
linkeddatahub-varnish-admin-1     | Debug: Version: varnish-6.0.11 revision a3bc025c2df28e4a76e10c2c41217c9864e9963b
linkeddatahub-varnish-admin-1     | Debug: Platform: Linux,5.15.49-linuxkit,x86_64,-junix,-smalloc,-sdefault,-hcritbit
linkeddatahub-varnish-end-user-1  | Debug: Version: varnish-6.0.11 revision a3bc025c2df28e4a76e10c2c41217c9864e9963b
linkeddatahub-varnish-end-user-1  | Debug: Platform: Linux,5.15.49-linuxkit,x86_64,-junix,-smalloc,-sdefault,-hcritbit
```

Even `./import-letsencrypt-stg-roots.sh` runs all right (tried multiple times).

**Comment by namedgraph** [comment]
@beepsoft can we consider this solved?

**Comment by beepsoft** [comment]
With Rosetta enabled it is ok now as a workaround until you are able to build arm images.
