### ISSUE TITLE
"Get started / Setup guide" incomplete in Documentation

### ISSUE THREAD

**Issue by damooo** [AtomGraph/LinkedDataHub#41]
When i launched with docker, linkeddatahub container crashes with error `Admin base URI and/or admin quad store could not be extracted from /WEB-INF/classes/com/atomgraph/linkeddatahub/system.trig for root app.` remaining other containers started properly.

**Comment by namedgraph** [comment]
Hi. How do you run the containers? Have you made any changes to the config?

I've just checked out a fresh copy and could not reproduce this.

**Comment by damooo** [comment]
I just followed instructions at https://linkeddatahub.com/linkeddatahub/docs/get-started/setup/ .

just cloned repo, created `.env` file, from `.env_sample` template, and did `docker-compose up` . All images built properly. and containers instantiated properly. But `linkeddatahub` crashes within few seconds.

**Comment by namedgraph** [comment]
OK stay with me :) I could be that this guide is incomplete...

Could you please look here? https://github.com/AtomGraph/LinkedDataHub#configuration

The error message says that the base URI built from your `.env` file (from `PROTOCOL`, ..., `ABS_PATH` components) does not align with the `ldt:base` values in `config/system.trig`? Could this be the case?

**Comment by damooo** [comment]
Yes, it is the case.

I set `PROTOCOL` to `http`, and `HTTP_PORT` to some custom value. in `config/system.trig`, the base-uri doesn't seems reflecting `PROTOCOL` in `.env`. It's proto is `https`, and port is that of `HTTPS_PORT` env var. I manually edited the file, and it is working now great. (btw, `OWNER_KEY_PASSWORD` should also be of minimum length 6, otherwise it will raise).

Thanks for great work.

**Comment by namedgraph** [comment]
@damooo there is this text on the Setup page though:
> This section assumes you will be running on your local machine, i.e. `localhost`. If you intend to run it on a different host, see the system base URI configuration.

Should it be more explicit? Or maybe formatted as a warning?

**Comment by damooo** [comment]
The host i run is `localhost` only. only port values, and protocal i changed.
