### ISSUE TITLE
Failed to execute script docker-compose

### ISSUE THREAD

**Issue by qhreul** [AtomGraph/LinkedDataHub#46]
When trying to the follow the [instructions](https://linkeddatahub.com/linkeddatahub/docs/get-started/setup/) to start LinkedDataHub, I encounter an error that prevent the application from starting (see [startup.log](https://github.com/AtomGraph/LinkedDataHub/files/5466886/startup.log)). As a note, I was running the docker image on MacOS 10.15.7.

Has this issue been experienced before?

**Comment by namedgraph** [comment]
@qhreul can you please confirm this is not a general `docker-compose` issue? Does not seem LDH related. I've seen similar on WSL (Ubuntu) on Windows.

**Comment by qhreul** [comment]
@namedgraph Please ignore my issue. It seems that I misconfigured my environment.
