### ISSUE TITLE
Signup - 500 error on create context link

### ISSUE THREAD

**Issue by stain** [AtomGraph/LinkedDataHub#7]
After signing up, Email says:

> When you're ready, proceed to create a context for your Linked Data applications by following this link: https://linkeddatahub.com/docs/create?forClass=https%3A%2F%2Flinkeddatahub.com%2Fdocs%2Fns%23Context
Read more about LinkedDataHub contexts here: https://linkeddatahub.com/docs/manage-apps#contexts

But this fails with:

```
HTTP Status 500 - com.sun.jersey.api.container.ContainerException: Unable to create resource class com.atomgraph.platform.server.impl.ResourceBase

root cause
...
com.atomgraph.processor.exception.ParameterException: Parameter 'forClass' not supported by Template '[<http://atomgraph.com/ns/platform/templates#Item>: "(.*)", 0.0]'
    com.atomgraph.processor.util.TemplateCall.applyArguments(TemplateCall.java:90)
```

Correct link should probably be https://linkeddatahub.com/create?forClass=https%3A%2F%2Flinkeddatahub.com%2Fns%23Context

**Comment by namedgraph** [comment]
If you signed up in the Documentation app, the link shouldn't be in the email as Documentation is not a Context per se, but a top-level app under the Root context.
