### ISSUE TITLE
If I'd like to translate the UI interface to other language, what should I do?

### ISSUE THREAD

**Issue by yiouyou** [AtomGraph/LinkedDataHub#77]
Beyond english, any productive way to turn the UI interface to other language? Thanks!

**Comment by namedgraph** [comment]
Hi! A place to start would be [`translations.rdf`](src/main/webapp/static/com/atomgraph/linkeddatahub/xsl/bootstrap/2.3.2/translations.rdf) which contains most of the strings in the UI. But I'm afraid not all, those would have to be found and replaced.

Then in addition to english labels like `<rdfs:label xml:lang="en-US">Search</rdfs:label>`, you could add labels in other language, for example `<rdfs:label xml:lang="zh">搜索</rdfs:label>` or something like that. Try to choose the right [language code](https://www.w3.org/International/questions/qa-choosing-language-tags).
@yiouyou can you do that?

And then we need a switch that would use the right labels based on the browser's locale. The [`Accept-Language`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) request can be used for that. I can take care of this part.

**Comment by yiouyou** [comment]
@namedgraph Yes, I can do the translation. Sorry for the dalay reply. I'll try to start from translations.rdf and see what I can do about it.

**Comment by namedgraph** [comment]
@yiouyou great! I'd be curious to hear about your use case :) You can contact me at martynas[at]atomgraph.com

**Comment by yiouyou** [comment]
@namedgraph Sure, will keep in touch. btw, thhe project is about pure RDF Knowledge Graph only or can it be run on some more sophisticated engines, such as Grakn?

**Comment by namedgraph** [comment]
It's only for RDF KG.

**Comment by namedgraph** [comment]
@yiouyou are you still up for the translation? :)

**Comment by namedgraph** [comment]
@yiouyou there's now an example with a Spanish translation. If you want to add another language, you can create a PR.
https://github.com/AtomGraph/LinkedDataHub/blob/master/src/main/webapp/static/com/atomgraph/linkeddatahub/xsl/bootstrap/2.3.2/translations.rdf
