### ISSUE TITLE
Use "/usr/bin/env bash" as interpreter in scripts

### ISSUE THREAD

**Issue by tmciver** [AtomGraph/LinkedDataHub#80]
It would be convenient to use the `#!/usr/bin/env bash` interpreter line at the top of all scripts so that they will work on systems where bash is on a different path.

My motivation for requesting this change is so that user scripts will work when run using [Nix](https://nixos.org/). Such user scripts typically leverage scripts in LDH and `bash` is not found under `/bin` when using Nix.  (I ran into this problem while developing [ldh-quotes app](https://github.com/tmciver/ldh-quotes-app).)

**Comment by namedgraph** [comment]
@tmciver I'll try this on the develop branch. If it works, then it's fine with me to merge #81.

**Comment by namedgraph** [comment]
@tmciver this is now merged to `develop`. Wanna check whether it works for you? Will try to do a new release ASAP.

**Comment by tmciver** [comment]
Yup, it works!  Thanks!
