### ISSUE TITLE
Implement Accept-Post and Accept-Put methods

### ISSUE THREAD

**Issue by namedgraph** [AtomGraph/LinkedDataHub#9]
https://tools.ietf.org/html/rfc7231#section-4.3.7
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS

**Comment by csarven** [comment]
Make sure to expose the following headers where applicable:
```
Allow
Accept-Post
Accept-Patch
Accept-Put
```

**Comment by namedgraph** [comment]
`Accept-Post` is semi-defined in the LDP spec: https://www.w3.org/TR/ldp/#header-accept-post

**Comment by namedgraph** [comment]
`Accept-Patch`: https://tools.ietf.org/html/rfc5789#section-4.1

**Comment by namedgraph** [comment]
I think the implementation should be:
* `Accept-Post` on Container resources (creates new child resource)
* `Accept-Put`, `Accept-Post`, `Accept-Patch` (SPARQL update) on named graphs

**Comment by namedgraph** [comment]
`OPTIONS` is supported by Jersey by default:

    OPTIONS /demo/city-graph/ HTTP/1.1
    Host: linkeddatahub.com:4443
    User-Agent: curl/7.47.0
    Accept: */*

    HTTP/1.1 200 OK
    Server: Apache-Coyote/1.1
    Strict-Transport-Security: max-age=31536000;includeSubDomains
    Allow: OPTIONS,HEAD,DELETE,POST,GET,PUT
    Last-modified: Wed, 19 Dec 2018 00:01:48 CET
    Vary: Accept
    Content-Type: application/vnd.sun.wadl+xml
    Content-Length: 1015
    Date: Thu, 20 Dec 2018 20:17:11 GMT

I'll look into the other headers now.

**Comment by namedgraph** [comment]
Looks like this is at implemented for the Graph Store Protocol with direct graph identification:
https://github.com/AtomGraph/LinkedDataHub/blob/master/src/main/java/com/atomgraph/linkeddatahub/resource/graph/Item.java#L106

**Comment by namedgraph** [comment]
```
pumba@LAPTOP-BL3MCU0O:~$ curl -k https://kgdev.net -X OPTIONS -I
HTTP/1.1 200
Server: nginx/1.21.4
Date: Thu, 17 Feb 2022 21:23:59 GMT
Content-Length: 0
Connection: keep-alive
Allow: GET
Allow: POST
Allow: PUT
Allow: DELETE
Accept-Post: text/html;charset=UTF-8,application/xhtml+xml;charset=UTF-8,application/rdf+xml;charset=UTF-8,application/n-triples;charset=UTF-8,application/rdf+protobuf;charset=UTF-8,application/trix;charset=UTF-8,application/ld+json;charset=UTF-8,x/ld-json-11;charset=UTF-8,text/shaclc;charset=UTF-8,application/rdf+thrift;charset=UTF-8,text/turtle;charset=UTF-8,text/rdf+n3;charset=UTF-8,application/rdf+json;charset=UTF-8
Link: <https://kgdev.net/>; rel=https://www.w3.org/ns/ldt#base
Link: <https://kgdev.net/sparql>; rel=http://www.w3.org/ns/sparql-service-description#endpoint
Link: <https://kgdev.net/admin/model/ontologies/namespace/#>; rel=https://www.w3.org/ns/ldt#ontology
```
