### ISSUE TITLE
Unable to start linkeddatahub_1 dependency in setup

### ISSUE THREAD

**Issue by sahith00** [AtomGraph/LinkedDataHub#90]
While following the setup section of the documentation to start LinkedDataHub (all prerequisites obtained), I'm unable to continue past step 4, which is to run the "docker-compose up" command, because of an error while starting/recreating the linkeddatahub_1 dependency. The error, which occurs multiple times, is "ILLEGAL_CHARACTER in PORT: The character violates the grammar rules for URIs/IRIs". Not sure why this is occurring since I'm not directly altering the URIs.
<img width="1278" alt="Screen Shot 2021-03-25 at 3 58 45 PM" src="https://user-images.githubusercontent.com/10366655/112554145-fcb64280-8d82-11eb-99bc-f02232160cda.png">

Another error when running "docker-compose up" (doesn't halt the execution of the command):
<img width="1277" alt="Screen Shot 2021-03-25 at 3 59 09 PM" src="https://user-images.githubusercontent.com/10366655/112554167-0a6bc800-8d83-11eb-8ab7-cf1f831c4e91.png">

(Running on macOS Catalina version 10.15.7)

**Comment by namedgraph** [comment]
Hi. You can see the base URI in the output: `secpwd://secpwd:secpwd` I guess. It's not gonna work over HTTP and it's not even a valid URI, as `riot` complains.

How does your `.env` file look? My guess you entered some values from which an illegal URL gets constructed.

The default config looks like this:
```
PROTOCOL=https
HTTP_PORT=81
HTTPS_PORT=4443
HOST=localhost
ABS_PATH=/
```
which goes into a template `"${PROTOCOL}://${HOST}:${HTTP_PROXY_PORT}${ABS_PATH}"` and produces base URI `https://localhost:4443/`.

You don't need to change this part of the config if you're just trying LinkedDataHub locally on your machine.

**Comment by sahith00** [comment]
Hi, thanks. This helped narrow down the issue for me. I realize now that I'm also running into issues when executing the setup.sh script. 
This is my env file:

<img width="352" alt="Screen Shot 2021-03-25 at 4 40 39 PM" src="https://user-images.githubusercontent.com/10366655/112557090-d7c4ce00-8d88-11eb-9369-2133c88d5a48.png">

The errors I'm running into with the setup.sh:

<img width="636" alt="Screen Shot 2021-03-25 at 4 42 10 PM" src="https://user-images.githubusercontent.com/10366655/112557167-0f337a80-8d89-11eb-8be9-bfc28b6464c1.png">

I haven't modified the setup.sh file since forking this repository, so I'm not sure why the errors are occurring. I'm currently using bash-3.2 to run the commands, please let me know if it could be an issue with the version.

**Comment by namedgraph** [comment]
Hi again. This looks like shell issue `declare -A` is a Bash 4 feature and you seem to be running 3.2. Would you be able to try Bash 4?
https://stackoverflow.com/a/691157/1003113

**Comment by namedgraph** [comment]
I should mention this in the `README`... This Bash 4 feature is only used in the `setup.sh` though, maybe it would be possible to avoid.

**Comment by sahith00** [comment]
Thank you! I've upgraded bash, and the declare -A command works for me now. However, the "unknown option -addext" error is still present, and I believe it's because my version of Openssl is also incorrect.

Current version:
<img width="113" alt="Screen Shot 2021-03-25 at 5 09 40 PM" src="https://user-images.githubusercontent.com/10366655/112558819-e4e3bc00-8d8c-11eb-8e18-10cb5755314d.png">

Do I need to upgrade openssl, or does the issue lie somewhere else?

**Comment by namedgraph** [comment]
Hmm, don't know if I can help much here, I know it works with OpenSSL 1.1.x, so if you can try that :) Not sure LibreSSL supports the `-addext` option...

**Comment by namedgraph** [comment]
@sahith00 let me know if you managed to solve it.

**Comment by sahith00** [comment]
Hi @namedgraph I installed OpenSSL 1.1.1k and used that to run the script, but the Base URI is still incorrect and I believe that has to do with the declare -A env line running incorrectly. On my Mac, the -A option for declare is an invalid option, and using -a makes it so that every value in the env variable is the value at the last line of my env file.

Some debugging I ran to reach this conclusion:
<img width="798" alt="Screen Shot 2021-03-28 at 4 13 12 PM" src="https://user-images.githubusercontent.com/10366655/112771398-81ea6300-8fe0-11eb-9aff-5f9e4e525ea4.png">

(Based on line 45 of the code and the last output line in terminal, env[OWNER_GIVEN_NAME] = secpwd, even though that's not the case in the .env file)

I believe this issue is cause by the difference between indexed arrays and associative arrays in bash, but I'm not sure how to solve it.

**Comment by namedgraph** [comment]
You installed Bash 5.1, I can see. But are you sure you're using it and not the old version? :) Check out this:
https://stackoverflow.com/questions/6047648/associative-arrays-error-declare-a-invalid-option

**Comment by sahith00** [comment]
Thank you! The bash version was the issue because I was using a path that pointed to an earlier version even though I also had the newest version installed somewhere else. I was able to setup the app, get an account, and run the app on Safari. Google Chrome seems to be unable to process the certificate, though.

Thank you so much for your help!

**Comment by namedgraph** [comment]
See this re. Chrome on MacOS:
https://github.com/AtomGraph/LinkedDataHub#notes

**Comment by namedgraph** [comment]
@sahith00 I'm closing the issue then. Thanks for your patience!
