### ISSUE TITLE
Execption when executing getting started tutorial

### ISSUE THREAD

**Issue by kleegrewec** [AtomGraph/LinkedDataHub#97]
When I follow the steps in the getting started documentation I get an exception when trying to clear the ontologies. 
The execption is thrown when I click on the Domain ontology in the ontologies list. 

The execption occurs when clicking on any of the ontologies.
-------------------8<--------------------------------------
Type Exception Report

Message java.lang.ClassCastException: class com.sun.proxy.$Proxy44 cannot be cast to class org.apache.jena.util.FileManager (com.sun.proxy.$Proxy44 is in unnamed module of loader org.jvnet.hk2.internal.DelegatingClassLoader @446c63b4; org.apache.jena.util.FileManager is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @5e01a982)

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: java.lang.ClassCastException: class com.sun.proxy.$Proxy44 cannot be cast to class org.apache.jena.util.FileManager (com.sun.proxy.$Proxy44 is in unnamed module of loader org.jvnet.hk2.internal.DelegatingClassLoader @446c63b4; org.apache.jena.util.FileManager is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @5e01a982)
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
Root Cause

java.lang.ClassCastException: class com.sun.proxy.$Proxy44 cannot be cast to class org.apache.jena.util.FileManager (com.sun.proxy.$Proxy44 is in unnamed module of loader org.jvnet.hk2.internal.DelegatingClassLoader @446c63b4; org.apache.jena.util.FileManager is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @5e01a982)
	com.atomgraph.linkeddatahub.server.model.impl.ResourceBase.describe(ResourceBase.java:942)
	com.atomgraph.core.model.impl.QueriedResourceBase.get(QueriedResourceBase.java:120)
	com.atomgraph.server.model.impl.ResourceBase.get(ResourceBase.java:227)
	com.atomgraph.linkeddatahub.server.model.impl.ResourceBase.get(ResourceBase.java:227)
	jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base/java.lang.reflect.Method.invoke(Method.java:566)
	org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
Note The full stack trace of the root cause is available in the server logs.

-------------------8<--------------------------------------

Any help to solve this is appreciated.

thanks Christian

[linkeddatahub_1.zip](https://github.com/AtomGraph/LinkedDataHub/files/6344310/linkeddatahub_1.zip)

![210420_LinkedDatahubException_v01](https://user-images.githubusercontent.com/28925154/115411669-f6857b80-a1f3-11eb-81f5-63ff66c8db92.PNG)

**Comment by namedgraph** [comment]
Thanks for giving it a try!

This is some proxy injection crap... Actually we just got rid of them in the `develop` branch. Could you check it out and build the Docker image? `docker build -t atomgraph/linkeddatahub .`

I'm planning to merge it in the next couple of days.

**Comment by kleegrewec** [comment]
Thanks for the answer. I think I will wait for the merged docker images.

Christian

**Comment by namedgraph** [comment]
@kleegrewec I just did a new release. Can you do a `docker-compose pull` (before `docker-compose up`) and try again?
